### ISSUE TITLE
Ability to print a song on paper, for easy transfer to physical music box

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/music-box-fun#16]
This would make transferring a song to a physical box more convenient and less error-prone. Other sites that play music box songs have this feature.

**Comment by dedou83** [comment]
Yes it's a very good idea !!! very useful ! :)

**Comment by bryanbraun** [comment]
This has been requested several times, so it's at the top of my priority list. If you need to print a song in the mean time, a workaround is to take a screenshot of the page (see [these instructions](https://zapier.com/blog/full-page-screenshots-in-chrome/)) and scale it for printing.

***

Dev notes: I think a first-pass would be to add a print-stylesheet, that makes the existing HTML more suitable for printing. In the future, if we want more robust printing, we could use the note data to generate a custom image that is only used for printing.

**Comment by bryanbraun** [comment]
This feature has been added. To print, use CMD+P or your browser's default print feature (usually found in File → Print). In the future, we can consider adding a dedicated "Print" button to the music-box-fun UI itself.
