### ISSUE TITLE
Ability to undo (CTRL+Z) and redo (CTRL+SHIFT+Z)

### ISSUE THREAD

**Issue by Sko-P** [bryanbraun/music-box-fun#24]
I put random notes all over a music sheet I worked on but unfortunately couldn't undo anything.

**Comment by bryanbraun** [comment]
Great idea! Currently, the back button should undo a song change and the forward button should redo it.

I'll bet there's a way to map CTRL+Z to "Back" and CTRL+SHIFT+Z to "Forward" which should resolve this issue.

**Comment by bryanbraun** [comment]
FYI, I just added this feature in c7f5c1c, and deployed it. Feel free to test it out on the live site. 😄
